name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.3.3
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  dio: ^5.3.2
  flutter_local_notifications: ^15.1.1
  rxdart: ^0.27.7

  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  package_info_plus: ^4.1.0
  open_filex: ^4.3.2
  sensors_plus: ^3.0.3
  share_plus: ^7.1.0
  chopper: ^7.0.6
  url_launcher: ^6.1.14

dev_dependencies:
  lint: ^2.1.2
